CREATE TABLE `LOCAL_MESSAGE` (
  `GUID` varchar(36) NOT NULL,
  `DESTINATION` varchar(50) NOT NULL,
  `MESSAGE` varchar(2000) NOT NULL,
  `STATUS` decimal(1,0) NOT NULL DEFAULT '0',
  `RETRY_TIMES` decimal(2,0) NOT NULL DEFAULT '0',
  `CREATE_TIME` decimal(19,0) NOT NULL,
  `LAST_PUSH_TIME` decimal(19,0) DEFAULT NULL,
  `FAILURE_REASON` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`GUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;